### ISSUE TITLE
Upon clicking "Collect" in a new TRU Collector, error message

### ISSUE THREAD

**Issue by floatingtim** [cogdog/tru-collector#12]
Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /home/megansbl/megantrublog.megansblog.bergbuilds.domains/wp-content/themes/trucollector/page-collect.php on line 31

**Comment by cogdog** [comment]
A PHP 8 change, sigh... This was fixed in GitHub version https://github.com/cogdog/tru-collector/commit/cd9cb0edf7c78ced2f1ced02e262df9f29885296  but am guessing this is via the Reclaim Hosting one? I need to converse with them to get a fix

**Comment by floatingtim** [comment]
I hadn't even thought about installing from github.  I'll do that, thank you.  And let me know if I can help get the installer updated from the Reclaim Hosting dashboard. Happy to do it.

**Comment by kyledenlinger** [comment]
Alan, did you ever connect with the Reclaim folks on this issue? I just walked a faculty member through it and am still getting the PHP error.

**Comment by cogdog** [comment]
Hi Kyle, we could not find a way to maintain the one click SPLOT installers- I have [instructions for how to update these](https://github.com/cogdog/splotlab/blob/master/guides/wordpress.md#updating-reclaim-hostings-custom-installed-splots)

I am not sure how you are providing install instructions for new splots, the best practice is now to (1)install new WordPress app and follow manual install options https://github.com/cogdog/splotlab/blob/master/guides/wordpress.md#start-with-the-parent-theme

Sorry about this!
